### ISSUE TITLE
root certificate for Atmel TPM device

### ISSUE THREAD

**Issue by cristianberneanu** [theopolis/tpm-i2c-atmel#1]
Hello,

I encountered this project while looking for the parent certificate for the Endorsement Key found on Atmel TPM devices. I can't find the CA certificate published anywhere and I'm wondering if you have any idea where I can find it.

The issuer's distinguished name for the extracted EK is: "C=US, ST=Colorado, L=Colorado Springs, O=Atmel, CN=Atmel Signing Module 22".

Thank you.

**Comment by theopolis** [comment]
Hey @cristianberneanu, as far as I know, there's no certificate within the various Atmel TPMs. For those TPMs that have an EK "pregenerated" (since you can purchase TPMs that have not blown their efuse to allow EK generation), Atmel has the opportunity to inspect the EK public key and thus generate a signed blob using some other private keying material they control.

That signed blob is not present in the TPM and I am not sure what process is available to retrieve it. The Privacy CA concept from the TPM 1.2 spec would be the request/authentication protocol for signed EK requests.

**Comment by cristianberneanu** [comment]
Hello @theopolis,

Thank you very much for this information. I could not get anything about this from Atmel's website or support channels. It is unfortunate that there is no way to remotely attest a machine having an Atmel TPM.

**Comment by theopolis** [comment]
I agree! You can low-key roll your own if you have a limited number of devices. Although I'm not the biggest fan of [OpenAttestation](https://github.com/OpenAttestation/OpenAttestation)'s development model, it's a good start! Limited to TPM 1.2 devices/API too.

**Comment by cristianberneanu** [comment]
Thanks, I will look into it.
Unless I can move to some other manufacturer that provides a valid trust chain for the EK, like Infineon.
